/*
  worldcup-data.js
  Base de dados do jogo.
  Formato compacto:
  "Nome|POSIÇÃO/ALTERNATIVA|OVERALL|tipo"
  tipo = titular_base ou reserva_principal
  Observação: base jogável/provisória para o game, não escalação oficial fixa.
*/
window.COPA_2026_BASE = [
  {id:"mex_2026",pais:"México",grupo:"A",jogadores:[
    "Guillermo Ochoa|GOL|84|titular_base","Jorge Sánchez|LD|79|titular_base","César Montes|ZAG|82|titular_base","Johan Vásquez|ZAG|81|titular_base","Jesús Gallardo|LE/ALA_E|79|titular_base","Edson Álvarez|VOL/ZAG|84|titular_base","Luis Chávez|MC/VOL|81|titular_base","Orbelín Pineda|MC/MEI|80|titular_base","Hirving Lozano|PD/PE|83|titular_base","Santiago Giménez|ATA|84|titular_base","Julián Quiñones|PE/ATA|82|titular_base","Raúl Jiménez|ATA|80|reserva_principal","Uriel Antuna|PD|78|reserva_principal","Erick Sánchez|MC|78|reserva_principal"]},
  {id:"rsa_2026",pais:"África do Sul",grupo:"A",jogadores:[
    "Ronwen Williams|GOL|80|titular_base","Khuliso Mudau|LD|77|titular_base","Siyanda Xulu|ZAG|76|titular_base","Mothobi Mvala|ZAG/VOL|76|titular_base","Aubrey Modiba|LE/ALA_E|77|titular_base","Teboho Mokoena|MC/VOL|81|titular_base","Sphephelo Sithole|VOL|77|titular_base","Themba Zwane|MEI|80|titular_base","Percy Tau|PD/SA|81|titular_base","Lyle Foster|ATA|80|titular_base","Evidence Makgopa|ATA|77|titular_base","Grant Kekana|ZAG|76|reserva_principal","Thapelo Morena|ALA_D/PD|76|reserva_principal","Zakhele Lepasa|ATA|75|reserva_principal"]},
  {id:"kor_2026",pais:"Coreia do Sul",grupo:"A",jogadores:[
    "Kim Seung-gyu|GOL|80|titular_base","Seol Young-woo|LD/LE|78|titular_base","Kim Min-jae|ZAG|88|titular_base","Kim Young-gwon|ZAG|80|titular_base","Lee Ki-je|LE|77|titular_base","Hwang In-beom|MC|82|titular_base","Park Yong-woo|VOL|78|titular_base","Lee Kang-in|MEI/PD|84|titular_base","Son Heung-min|PE/ATA|89|titular_base","Hwang Hee-chan|PD/ATA|84|titular_base","Cho Gue-sung|ATA|80|titular_base","Jeong Woo-yeong|MEI/PE|78|reserva_principal","Hong Hyun-seok|MC|77|reserva_principal","Oh Hyeon-gyu|ATA|77|reserva_principal"]},
  {id:"cze_2026",pais:"Tchéquia",grupo:"A",jogadores:[
    "Jindřich Staněk|GOL|79|titular_base","Vladimír Coufal|LD|81|titular_base","Tomáš Holeš|ZAG/VOL|79|titular_base","Ladislav Krejčí|ZAG/VOL|82|titular_base","David Jurásek|LE/ALA_E|78|titular_base","Tomáš Souček|VOL/MC|84|titular_base","Michal Sadílek|MC/VOL|79|titular_base","Antonín Barák|MEI/MC|81|titular_base","Václav Černý|PD|79|titular_base","Adam Hložek|SA/ATA|81|titular_base","Patrik Schick|ATA|85|titular_base","Lukáš Provod|ME/MC|79|reserva_principal","Mojmír Chytil|ATA|77|reserva_principal","Ondřej Lingr|MEI|77|reserva_principal"]},

  {id:"can_2026",pais:"Canadá",grupo:"B",jogadores:[
    "Dayne St. Clair|GOL|77|titular_base","Alistair Johnston|LD/ZAG|80|titular_base","Moïse Bombito|ZAG|78|titular_base","Derek Cornelius|ZAG|77|titular_base","Alphonso Davies|LE/ALA_E/PE|87|titular_base","Stephen Eustáquio|MC/VOL|82|titular_base","Ismaël Koné|MC|80|titular_base","Jonathan Osorio|MEI/MC|78|titular_base","Tajon Buchanan|PD/ALA_D|82|titular_base","Jonathan David|ATA/SA|86|titular_base","Cyle Larin|ATA|81|titular_base","Maxime Crépeau|GOL|76|reserva_principal","Liam Millar|PE|77|reserva_principal","Jacob Shaffelburg|PE/ALA_E|77|reserva_principal"]},
  {id:"bih_2026",pais:"Bósnia e Herzegovina",grupo:"B",jogadores:[
    "Ibrahim Šehić|GOL|77|titular_base","Jusuf Gazibegović|LD|78|titular_base","Anel Ahmedhodžić|ZAG|82|titular_base","Dennis Hadžikadunić|ZAG|78|titular_base","Sead Kolašinac|LE/ZAG|82|titular_base","Rade Krunić|MC/VOL|81|titular_base","Amir Hadžiahmetović|VOL|78|titular_base","Benjamin Tahirović|MC|78|titular_base","Miroslav Stevanović|MD/PD|78|titular_base","Edin Džeko|ATA|83|titular_base","Ermedin Demirović|ATA/SA|82|titular_base","Haris Tabaković|ATA|79|reserva_principal","Smail Prevljak|ATA|77|reserva_principal","Amer Gojak|MEI|77|reserva_principal"]},
  {id:"qat_2026",pais:"Catar",grupo:"B",jogadores:[
    "Meshaal Barsham|GOL|77|titular_base","Pedro Miguel|LD/ZAG|77|titular_base","Boualem Khoukhi|ZAG/VOL|78|titular_base","Tarek Salman|ZAG|76|titular_base","Abdelkarim Hassan|LE/ALA_E|79|titular_base","Assim Madibo|VOL|76|titular_base","Karim Boudiaf|MC|77|titular_base","Akram Afif|PE/MEI|84|titular_base","Hassan Al-Haydos|MEI/PD|79|titular_base","Almoez Ali|ATA|81|titular_base","Yusuf Abdurisag|ATA/PD|76|titular_base","Saad Al-Sheeb|GOL|76|reserva_principal","Mohammed Waad|MC|75|reserva_principal","Ahmed Alaaeldin|ATA|75|reserva_principal"]},
  {id:"sui_2026",pais:"Suíça",grupo:"B",jogadores:[
    "Yann Sommer|GOL|85|titular_base","Silvan Widmer|LD/ALA_D|80|titular_base","Manuel Akanji|ZAG|85|titular_base","Nico Elvedi|ZAG|82|titular_base","Ricardo Rodríguez|LE/ZAG|81|titular_base","Granit Xhaka|VOL/MC|86|titular_base","Remo Freuler|MC/VOL|82|titular_base","Denis Zakaria|VOL/MC|81|titular_base","Xherdan Shaqiri|MEI/PD|81|titular_base","Breel Embolo|ATA|82|titular_base","Ruben Vargas|PE/PD|80|titular_base","Gregor Kobel|GOL|86|reserva_principal","Zeki Amdouni|ATA/SA|80|reserva_principal","Fabian Rieder|MC/MEI|79|reserva_principal"]},

  {id:"bra_2026",pais:"Brasil",grupo:"C",jogadores:[
    "Alisson|GOL|90|titular_base","Danilo|LD/ZAG|82|titular_base","Marquinhos|ZAG|88|titular_base","Gabriel Magalhães|ZAG|87|titular_base","Alex Sandro|LE|80|titular_base","Casemiro|VOL|86|titular_base","Bruno Guimarães|MC/VOL|87|titular_base","Lucas Paquetá|MEI/MC|84|titular_base","Raphinha|PD/PE|87|titular_base","Vinicius Junior|PE/ATA|92|titular_base","Matheus Cunha|ATA/SA|84|titular_base","Neymar Junior|MEI/SA/PE|88|reserva_principal","Endrick|ATA|82|reserva_principal","Gabriel Martinelli|PE/PD|84|reserva_principal"]},
  {id:"mar_2026",pais:"Marrocos",grupo:"C",jogadores:[
    "Yassine Bounou|GOL|85|titular_base","Achraf Hakimi|LD/ALA_D|88|titular_base","Nayef Aguerd|ZAG|82|titular_base","Romain Saïss|ZAG|81|titular_base","Noussair Mazraoui|LE/LD|84|titular_base","Sofyan Amrabat|VOL|83|titular_base","Azzedine Ounahi|MC|81|titular_base","Bilal El Khannouss|MEI/MC|82|titular_base","Hakim Ziyech|PD/MEI|83|titular_base","Youssef En-Nesyri|ATA|83|titular_base","Brahim Díaz|MEI/PE|86|titular_base","Amine Harit|MEI|80|reserva_principal","Abde Ezzalzouli|PE|80|reserva_principal","Ayoub El Kaabi|ATA|80|reserva_principal"]},
  {id:"hti_2026",pais:"Haiti",grupo:"C",jogadores:[
    "Johny Placide|GOL|76|titular_base","Carlens Arcus|LD|77|titular_base","Ricardo Adé|ZAG|76|titular_base","Mechack Jérôme|ZAG|75|titular_base","Alex Christian|LE|75|titular_base","Bryan Alceus|VOL|75|titular_base","Danley Jean Jacques|MC|78|titular_base","Leverton Pierre|MC|75|titular_base","Derrick Etienne Jr.|PE/PD|78|titular_base","Duckens Nazon|ATA|80|titular_base","Frantzdy Pierrot|ATA|79|titular_base","Fafà Picault|PE/ATA|77|reserva_principal","Carnejy Antoine|ATA|75|reserva_principal","Steeven Saba|MEI|75|reserva_principal"]},
  {id:"sco_2026",pais:"Escócia",grupo:"C",jogadores:[
    "Angus Gunn|GOL|79|titular_base","Aaron Hickey|LD/LE|81|titular_base","Jack Hendry|ZAG|78|titular_base","Scott McKenna|ZAG|78|titular_base","Andy Robertson|LE/ALA_E|86|titular_base","Billy Gilmour|MC/VOL|80|titular_base","Scott McTominay|MC/MEI|84|titular_base","John McGinn|MC/MEI|83|titular_base","Ryan Christie|MEI/PE|79|titular_base","Che Adams|ATA|80|titular_base","Lyndon Dykes|ATA|78|titular_base","Kieran Tierney|ZAG/LE|82|reserva_principal","Lewis Ferguson|MC|81|reserva_principal","Ben Doak|PD|78|reserva_principal"]},

  {id:"usa_2026",pais:"Estados Unidos",grupo:"D",jogadores:[
    "Matt Turner|GOL|80|titular_base","Sergiño Dest|LD/ALA_D|82|titular_base","Chris Richards|ZAG|81|titular_base","Tim Ream|ZAG|79|titular_base","Antonee Robinson|LE|83|titular_base","Tyler Adams|VOL|82|titular_base","Weston McKennie|MC|83|titular_base","Yunus Musah|MC|81|titular_base","Christian Pulisic|PE/PD|87|titular_base","Folarin Balogun|ATA|82|titular_base","Timothy Weah|PD/ALA_D|81|titular_base","Gio Reyna|MEI/PD|82|reserva_principal","Ricardo Pepi|ATA|80|reserva_principal","Brenden Aaronson|MEI/PE|79|reserva_principal"]},
  {id:"par_2026",pais:"Paraguai",grupo:"D",jogadores:[
    "Gatito Fernández|GOL|78|titular_base","Gustavo Gómez|ZAG|84|titular_base","Fabián Balbuena|ZAG|80|titular_base","Omar Alderete|ZAG|80|titular_base","Junior Alonso|LE/ZAG|79|titular_base","Mathías Villasanti|MC/VOL|80|titular_base","Andrés Cubas|VOL|78|titular_base","Miguel Almirón|MEI/PD|82|titular_base","Julio Enciso|PE/MEI|84|titular_base","Ramón Sosa|PE|81|titular_base","Antonio Sanabria|ATA|80|titular_base","Diego Gómez|MC/MEI|80|reserva_principal","Adam Bareiro|ATA|77|reserva_principal","Robert Rojas|LD/ZAG|77|reserva_principal"]},
  {id:"aus_2026",pais:"Austrália",grupo:"D",jogadores:[
    "Mathew Ryan|GOL|80|titular_base","Nathaniel Atkinson|LD|76|titular_base","Harry Souttar|ZAG|79|titular_base","Kye Rowles|ZAG|77|titular_base","Aziz Behich|LE|77|titular_base","Jackson Irvine|MC|80|titular_base","Keanu Baccus|VOL|77|titular_base","Riley McGree|MEI/MC|79|titular_base","Craig Goodwin|PE|78|titular_base","Mitchell Duke|ATA|78|titular_base","Martin Boyle|PD/ATA|77|titular_base","Joe Gauci|GOL|75|reserva_principal","Ajdin Hrustic|MEI|78|reserva_principal","Nestory Irankunda|PD|77|reserva_principal"]},
  {id:"tur_2026",pais:"Turquia",grupo:"D",jogadores:[
    "Uğurcan Çakır|GOL|81|titular_base","Zeki Çelik|LD|80|titular_base","Merih Demiral|ZAG|82|titular_base","Çağlar Söyüncü|ZAG|81|titular_base","Ferdi Kadıoğlu|LE/LD|84|titular_base","Hakan Çalhanoğlu|MC/VOL|87|titular_base","İsmail Yüksek|VOL|80|titular_base","Orkun Kökçü|MC/MEI|83|titular_base","Arda Güler|MEI/PD|86|titular_base","Kerem Aktürkoğlu|PE|82|titular_base","Barış Alper Yılmaz|ATA/PD|81|titular_base","Cenk Tosun|ATA|78|reserva_principal","Yunus Akgün|PD|79|reserva_principal","Kenan Yıldız|SA/PE|82|reserva_principal"]},

  {id:"ger_2026",pais:"Alemanha",grupo:"E",jogadores:[
    "Manuel Neuer|GOL|86|titular_base","Joshua Kimmich|LD/MC/VOL|88|titular_base","Antonio Rüdiger|ZAG|87|titular_base","Jonathan Tah|ZAG|84|titular_base","David Raum|LE/ALA_E|82|titular_base","Robert Andrich|VOL|82|titular_base","Toni Kroos|MC|89|titular_base","Jamal Musiala|MEI/PE|90|titular_base","Florian Wirtz|MEI/PD|90|titular_base","Leroy Sané|PD/PE|85|titular_base","Kai Havertz|ATA/MEI|85|titular_base","Marc-André ter Stegen|GOL|87|reserva_principal","İlkay Gündoğan|MC/MEI|85|reserva_principal","Niclas Füllkrug|ATA|82|reserva_principal"]},
  {id:"cuw_2026",pais:"Curaçao",grupo:"E",jogadores:[
    "Eloy Room|GOL|75|titular_base","Jurich Carolina|LE|75|titular_base","Cuco Martina|ZAG/LD|76|titular_base","Darryl Lachman|ZAG|75|titular_base","Roshon van Eijma|ZAG|75|titular_base","Leandro Bacuna|MC/LD|78|titular_base","Juninho Bacuna|MC/MEI|79|titular_base","Godfried Roemeratoe|VOL|76|titular_base","Brandley Kuwas|PD/PE|77|titular_base","Rangelo Janga|ATA|76|titular_base","Gervane Kastaneer|PE/ATA|75|titular_base","Kenji Gorré|PE|75|reserva_principal","Jeremy Antonisse|PE|75|reserva_principal","Vurnon Anita|VOL/LD|76|reserva_principal"]},
  {id:"civ_2026",pais:"Costa do Marfim",grupo:"E",jogadores:[
    "Yahia Fofana|GOL|78|titular_base","Serge Aurier|LD|80|titular_base","Ousmane Diomande|ZAG|82|titular_base","Evan Ndicka|ZAG|83|titular_base","Ghislain Konan|LE|78|titular_base","Franck Kessié|MC/VOL|84|titular_base","Ibrahim Sangaré|VOL|82|titular_base","Seko Fofana|MC|83|titular_base","Nicolas Pépé|PD|80|titular_base","Sébastien Haller|ATA|82|titular_base","Simon Adingra|PE|82|titular_base","Wilfried Singo|LD/ZAG|81|reserva_principal","Karim Konaté|ATA|79|reserva_principal","Amad Diallo|PD/MEI|82|reserva_principal"]},
  {id:"ecu_2026",pais:"Equador",grupo:"E",jogadores:[
    "Hernán Galíndez|GOL|78|titular_base","Ángelo Preciado|LD|80|titular_base","Félix Torres|ZAG|80|titular_base","Willian Pacho|ZAG|84|titular_base","Pervis Estupiñán|LE|84|titular_base","Moisés Caicedo|VOL/MC|88|titular_base","Alan Franco|MC/VOL|78|titular_base","Kendry Páez|MEI|82|titular_base","Gonzalo Plata|PD|80|titular_base","Enner Valencia|ATA|82|titular_base","Jeremy Sarmiento|PE/MEI|79|titular_base","Piero Hincapié|ZAG/LE|84|reserva_principal","Kevin Rodríguez|ATA|77|reserva_principal","Carlos Gruezo|VOL|78|reserva_principal"]},

  {id:"ned_2026",pais:"Holanda",grupo:"F",jogadores:[
    "Bart Verbruggen|GOL|82|titular_base","Denzel Dumfries|LD/ALA_D|84|titular_base","Matthijs de Ligt|ZAG|85|titular_base","Virgil van Dijk|ZAG|89|titular_base","Nathan Aké|LE/ZAG|84|titular_base","Frenkie de Jong|MC/VOL|88|titular_base","Tijjani Reijnders|MC|84|titular_base","Xavi Simons|MEI/PD|86|titular_base","Cody Gakpo|PE/ATA|85|titular_base","Memphis Depay|ATA/SA|83|titular_base","Donyell Malen|PD/ATA|82|titular_base","Micky van de Ven|ZAG/LE|84|reserva_principal","Ryan Gravenberch|MC|83|reserva_principal","Jeremie Frimpong|ALA_D/PD|84|reserva_principal"]},
  {id:"jpn_2026",pais:"Japão",grupo:"F",jogadores:[
    "Zion Suzuki|GOL|79|titular_base","Yukinari Sugawara|LD|80|titular_base","Takehiro Tomiyasu|ZAG/LD|84|titular_base","Ko Itakura|ZAG|81|titular_base","Hiroki Ito|LE/ZAG|81|titular_base","Wataru Endo|VOL|82|titular_base","Ao Tanaka|MC|79|titular_base","Takefusa Kubo|PD/MEI|85|titular_base","Kaoru Mitoma|PE|85|titular_base","Takumi Minamino|MEI/SA|82|titular_base","Ayase Ueda|ATA|79|titular_base","Daichi Kamada|MEI|82|reserva_principal","Ritsu Doan|PD|81|reserva_principal","Daizen Maeda|PE/ATA|80|reserva_principal"]},
  {id:"swe_2026",pais:"Suécia",grupo:"F",jogadores:[
    "Robin Olsen|GOL|79|titular_base","Emil Krafth|LD|77|titular_base","Victor Lindelöf|ZAG|82|titular_base","Isak Hien|ZAG|80|titular_base","Ludwig Augustinsson|LE|78|titular_base","Albin Ekdal|VOL|77|titular_base","Mattias Svanberg|MC|80|titular_base","Emil Forsberg|MEI/PE|81|titular_base","Dejan Kulusevski|PD/MEI|85|titular_base","Alexander Isak|ATA|87|titular_base","Viktor Gyökeres|ATA|86|titular_base","Anthony Elanga|PE/PD|81|reserva_principal","Jens Cajuste|MC/VOL|78|reserva_principal","Jesper Karlsson|PE|79|reserva_principal"]},
  {id:"tun_2026",pais:"Tunísia",grupo:"F",jogadores:[
    "Aymen Dahmen|GOL|76|titular_base","Wajdi Kechrida|LD|76|titular_base","Montassar Talbi|ZAG|80|titular_base","Dylan Bronn|ZAG|78|titular_base","Ali Maâloul|LE|78|titular_base","Ellyes Skhiri|VOL/MC|82|titular_base","Aïssa Laïdouni|MC|80|titular_base","Hannibal Mejbri|MC/MEI|78|titular_base","Anis Ben Slimane|MEI|78|titular_base","Youssef Msakni|PE/SA|80|titular_base","Seifeddine Jaziri|ATA|77|titular_base","Naïm Sliti|PE/MEI|78|reserva_principal","Elias Achouri|PE|77|reserva_principal","Hamza Rafia|MEI|76|reserva_principal"]},

  {id:"bel_2026",pais:"Bélgica",grupo:"G",jogadores:[
    "Thibaut Courtois|GOL|89|titular_base","Timothy Castagne|LD/LE|81|titular_base","Wout Faes|ZAG|80|titular_base","Arthur Theate|ZAG/LE|82|titular_base","Maxim De Cuyper|LE|80|titular_base","Amadou Onana|VOL/MC|83|titular_base","Youri Tielemans|MC|83|titular_base","Kevin De Bruyne|MEI/MC|91|titular_base","Jérémy Doku|PE/PD|84|titular_base","Romelu Lukaku|ATA|85|titular_base","Leandro Trossard|PE/SA|84|titular_base","Charles De Ketelaere|MEI/ATA|82|reserva_principal","Loïs Openda|ATA|83|reserva_principal","Johan Bakayoko|PD|82|reserva_principal"]},
  {id:"egy_2026",pais:"Egito",grupo:"G",jogadores:[
    "Mohamed El Shenawy|GOL|80|titular_base","Mohamed Hany|LD|76|titular_base","Ahmed Hegazi|ZAG|79|titular_base","Mohamed Abdelmonem|ZAG|80|titular_base","Ahmed Fatouh|LE|77|titular_base","Hamdi Fathi|VOL|77|titular_base","Mohamed Elneny|MC/VOL|78|titular_base","Emam Ashour|MC/MEI|78|titular_base","Mohamed Salah|PD/ATA|91|titular_base","Mostafa Mohamed|ATA|80|titular_base","Omar Marmoush|PE/ATA|85|titular_base","Trézéguet|PE|79|reserva_principal","Zizo|PD/MEI|78|reserva_principal","Mahmoud Hamada|MC|75|reserva_principal"]},
  {id:"iri_2026",pais:"Irã",grupo:"G",jogadores:[
    "Alireza Beiranvand|GOL|79|titular_base","Sadegh Moharrami|LD|77|titular_base","Morteza Pouraliganji|ZAG|78|titular_base","Majid Hosseini|ZAG|78|titular_base","Milad Mohammadi|LE|77|titular_base","Saeid Ezatolahi|VOL|78|titular_base","Saman Ghoddos|MC/MEI|78|titular_base","Ali Gholizadeh|PD/MEI|78|titular_base","Mehdi Taremi|ATA/SA|84|titular_base","Sardar Azmoun|ATA|83|titular_base","Alireza Jahanbakhsh|PE/PD|79|titular_base","Mehdi Ghayedi|PE|76|reserva_principal","Mohammad Mohebi|ATA/PD|76|reserva_principal","Omid Noorafkan|LE/VOL|76|reserva_principal"]},
  {id:"nzl_2026",pais:"Nova Zelândia",grupo:"G",jogadores:[
    "Max Crocombe|GOL|75|titular_base","Tim Payne|LD|75|titular_base","Michael Boxall|ZAG|75|titular_base","Nando Pijnaker|ZAG|75|titular_base","Liberato Cacace|LE|78|titular_base","Joe Bell|MC/VOL|76|titular_base","Marko Stamenic|MC|78|titular_base","Sarpreet Singh|MEI|77|titular_base","Matthew Garbett|MEI/MC|76|titular_base","Chris Wood|ATA|81|titular_base","Elijah Just|PE/PD|75|titular_base","Ryan Thomas|MC|76|reserva_principal","Ben Waine|ATA|75|reserva_principal","Finn Surman|ZAG|75|reserva_principal"]},

  {id:"esp_2026",pais:"Espanha",grupo:"H",jogadores:[
    "Unai Simón|GOL|84|titular_base","Dani Carvajal|LD|85|titular_base","Robin Le Normand|ZAG|84|titular_base","Aymeric Laporte|ZAG|84|titular_base","Alejandro Grimaldo|LE/ALA_E|85|titular_base","Rodri|VOL|92|titular_base","Pedri|MC/MEI|88|titular_base","Fabián Ruiz|MC|85|titular_base","Lamine Yamal|PD|89|titular_base","Álvaro Morata|ATA|84|titular_base","Nico Williams|PE|86|titular_base","Dani Olmo|MEI/PE|85|reserva_principal","Gavi|MC/MEI|85|reserva_principal","Ferran Torres|PD/ATA|82|reserva_principal"]},
  {id:"cpv_2026",pais:"Cabo Verde",grupo:"H",jogadores:[
    "Vozinha|GOL|76|titular_base","Steven Moreira|LD|77|titular_base","Logan Costa|ZAG|81|titular_base","Roberto Lopes|ZAG|76|titular_base","Dylan Tavares|LE|76|titular_base","Patrick Andrade|MC/VOL|76|titular_base","Jamiro Monteiro|MC/MEI|77|titular_base","Kevin Pina|VOL|76|titular_base","Jovane Cabral|PE/PD|78|titular_base","Ryan Mendes|PE/SA|78|titular_base","Djaniny|ATA|77|titular_base","Bebé|ATA/PD|76|reserva_principal","Garry Rodrigues|PE|76|reserva_principal","Willy Semedo|PD|75|reserva_principal"]},
  {id:"ksa_2026",pais:"Arábia Saudita",grupo:"H",jogadores:[
    "Mohammed Al-Owais|GOL|77|titular_base","Saud Abdulhamid|LD|79|titular_base","Ali Al-Bulaihi|ZAG|77|titular_base","Hassan Tambakti|ZAG|78|titular_base","Yasser Al-Shahrani|LE|77|titular_base","Mohamed Kanno|MC/VOL|78|titular_base","Salman Al-Faraj|MC|78|titular_base","Abdulelah Al-Malki|VOL|76|titular_base","Salem Al-Dawsari|PE|81|titular_base","Firas Al-Buraikan|ATA|78|titular_base","Saleh Al-Shehri|ATA|77|titular_base","Nawaf Al-Aqidi|GOL|76|reserva_principal","Abdulrahman Ghareeb|PE|76|reserva_principal","Ayman Yahya|PD|76|reserva_principal"]},
  {id:"uru_2026",pais:"Uruguai",grupo:"H",jogadores:[
    "Sergio Rochet|GOL|81|titular_base","Nahitan Nández|LD/MC|82|titular_base","Ronald Araújo|ZAG/LD|88|titular_base","José María Giménez|ZAG|85|titular_base","Mathías Olivera|LE/ZAG|82|titular_base","Manuel Ugarte|VOL|85|titular_base","Federico Valverde|MC|90|titular_base","Rodrigo Bentancur|MC|84|titular_base","Facundo Pellistri|PD|80|titular_base","Darwin Núñez|ATA|85|titular_base","Maximiliano Araújo|PE/ALA_E|81|titular_base","Luis Suárez|ATA|80|reserva_principal","Giorgian De Arrascaeta|MEI|83|reserva_principal","Nicolás de la Cruz|MC/MEI|82|reserva_principal"]},

  {id:"fra_2026",pais:"França",grupo:"I",jogadores:[
    "Mike Maignan|GOL|87|titular_base","Jules Koundé|LD/ZAG|85|titular_base","William Saliba|ZAG|88|titular_base","Dayot Upamecano|ZAG|84|titular_base","Theo Hernández|LE/ALA_E|86|titular_base","Aurélien Tchouaméni|VOL/MC|86|titular_base","Eduardo Camavinga|MC/VOL|85|titular_base","Antoine Griezmann|MEI/SA|87|titular_base","Ousmane Dembélé|PD/PE|86|titular_base","Kylian Mbappé|PE/ATA|95|titular_base","Marcus Thuram|ATA/PE|84|titular_base","Warren Zaïre-Emery|MC|84|reserva_principal","Kingsley Coman|PE/PD|84|reserva_principal","Randal Kolo Muani|ATA|82|reserva_principal"]},
  {id:"sen_2026",pais:"Senegal",grupo:"I",jogadores:[
    "Édouard Mendy|GOL|82|titular_base","Youssouf Sabaly|LD|79|titular_base","Kalidou Koulibaly|ZAG|84|titular_base","Moussa Niakhaté|ZAG|81|titular_base","Ismail Jakobs|LE|80|titular_base","Idrissa Gueye|VOL/MC|81|titular_base","Pape Matar Sarr|MC|82|titular_base","Nampalys Mendy|VOL|79|titular_base","Ismaïla Sarr|PD|82|titular_base","Nicolas Jackson|ATA|83|titular_base","Sadio Mané|PE/ATA|85|titular_base","Iliman Ndiaye|SA/MEI|81|reserva_principal","Habib Diallo|ATA|79|reserva_principal","Krépin Diatta|PD/ALA_D|79|reserva_principal"]},
  {id:"irq_2026",pais:"Iraque",grupo:"I",jogadores:[
    "Jalal Hassan|GOL|75|titular_base","Hussein Ali|LD|75|titular_base","Saad Natiq|ZAG|75|titular_base","Rebin Sulaka|ZAG|75|titular_base","Merchas Doski|LE|76|titular_base","Amir Al-Ammari|MC/VOL|77|titular_base","Osama Rashid|MC|76|titular_base","Ibrahim Bayesh|MEI/PD|76|titular_base","Ali Jasim|PE|78|titular_base","Aymen Hussein|ATA|79|titular_base","Mohannad Ali|ATA|76|titular_base","Zidane Iqbal|MC/MEI|78|reserva_principal","Bashar Resan|MC|76|reserva_principal","Mohanad Jeahze|LE|75|reserva_principal"]},
  {id:"nor_2026",pais:"Noruega",grupo:"I",jogadores:[
    "Ørjan Nyland|GOL|78|titular_base","Marcus Pedersen|LD|78|titular_base","Leo Østigård|ZAG|80|titular_base","Kristoffer Ajer|ZAG|80|titular_base","Fredrik Bjørkan|LE|77|titular_base","Sander Berge|VOL/MC|82|titular_base","Patrick Berg|MC/VOL|78|titular_base","Martin Ødegaard|MEI/MC|90|titular_base","Antonio Nusa|PE/PD|82|titular_base","Erling Haaland|ATA|94|titular_base","Alexander Sørloth|ATA|84|titular_base","Oscar Bobb|PD/MEI|81|reserva_principal","Morten Thorsby|MC|78|reserva_principal","Julian Ryerson|LD/LE|80|reserva_principal"]},

  {id:"arg_2026",pais:"Argentina",grupo:"J",jogadores:[
    "Emiliano Martínez|GOL|87|titular_base","Nahuel Molina|LD|82|titular_base","Cristian Romero|ZAG|88|titular_base","Nicolás Otamendi|ZAG|83|titular_base","Nicolás Tagliafico|LE|81|titular_base","Rodrigo De Paul|MC|84|titular_base","Enzo Fernández|MC/VOL|85|titular_base","Alexis Mac Allister|MC/MEI|87|titular_base","Lionel Messi|MEI/SA/PD|91|titular_base","Lautaro Martínez|ATA|88|titular_base","Julián Álvarez|ATA/SA|87|titular_base","Ángel Di María|PD/MEI|83|reserva_principal","Paulo Dybala|SA/MEI|84|reserva_principal","Alejandro Garnacho|PE|82|reserva_principal"]},
  {id:"dza_2026",pais:"Argélia",grupo:"J",jogadores:[
    "Anthony Mandrea|GOL|77|titular_base","Youcef Atal|LD|79|titular_base","Aïssa Mandi|ZAG|79|titular_base","Ramy Bensebaini|ZAG/LE|81|titular_base","Rayan Aït-Nouri|LE|83|titular_base","Ismaël Bennacer|MC/VOL|83|titular_base","Nabil Bentaleb|MC|80|titular_base","Houssem Aouar|MEI/MC|81|titular_base","Riyad Mahrez|PD/MEI|84|titular_base","Amine Gouiri|ATA/SA|82|titular_base","Mohamed Amoura|ATA/PE|82|titular_base","Baghdad Bounedjah|ATA|78|reserva_principal","Adam Ounas|PD|78|reserva_principal","Farès Chaïbi|MEI/PD|80|reserva_principal"]},
  {id:"aut_2026",pais:"Áustria",grupo:"J",jogadores:[
    "Patrick Pentz|GOL|78|titular_base","Stefan Posch|LD/ZAG|81|titular_base","Kevin Danso|ZAG|82|titular_base","Maximilian Wöber|ZAG/LE|80|titular_base","Philipp Mwene|LE/LD|79|titular_base","Konrad Laimer|MC/VOL|84|titular_base","Nicolas Seiwald|VOL/MC|81|titular_base","Marcel Sabitzer|MC/MEI|84|titular_base","Christoph Baumgartner|MEI/SA|82|titular_base","Michael Gregoritsch|ATA|80|titular_base","Marko Arnautović|ATA|79|titular_base","David Alaba|ZAG/MC/LE|84|reserva_principal","Romano Schmid|MEI|80|reserva_principal","Patrick Wimmer|PD/PE|79|reserva_principal"]},
  {id:"jor_2026",pais:"Jordânia",grupo:"J",jogadores:[
    "Yazeed Abulaila|GOL|75|titular_base","Ehsan Haddad|LD|75|titular_base","Yazan Al-Arab|ZAG|76|titular_base","Abdallah Nasib|ZAG|75|titular_base","Mohammad Abu Hasheesh|LE|75|titular_base","Nizar Al-Rashdan|VOL/MC|76|titular_base","Noor Al-Rawabdeh|MC|76|titular_base","Mousa Al-Taamari|PD/MEI|80|titular_base","Ali Olwan|ATA/PE|77|titular_base","Yazan Al-Naimat|ATA|79|titular_base","Mahmoud Mardi|PE|76|titular_base","Ibrahim Sadeh|MC|75|reserva_principal","Saleh Ratib|MEI|75|reserva_principal","Anas Al-Awadat|PD|75|reserva_principal"]},

  {id:"por_2026",pais:"Portugal",grupo:"K",jogadores:[
    "Diogo Costa|GOL|86|titular_base","João Cancelo|LD/LE|86|titular_base","Rúben Dias|ZAG|89|titular_base","António Silva|ZAG|84|titular_base","Nuno Mendes|LE/ALA_E|86|titular_base","João Palhinha|VOL|84|titular_base","Vitinha|MC|87|titular_base","Bruno Fernandes|MEI/MC|89|titular_base","Bernardo Silva|PD/MEI|88|titular_base","Rafael Leão|PE|86|titular_base","Cristiano Ronaldo|ATA|85|titular_base","Gonçalo Ramos|ATA|82|reserva_principal","Diogo Jota|ATA/PE|84|reserva_principal","João Félix|SA/MEI|82|reserva_principal"]},
  {id:"cod_2026",pais:"RD Congo",grupo:"K",jogadores:[
    "Lionel Mpasi|GOL|76|titular_base","Gédéon Kalulu|LD|77|titular_base","Chancel Mbemba|ZAG|83|titular_base","Dylan Batubinsika|ZAG|78|titular_base","Arthur Masuaku|LE|78|titular_base","Samuel Moutoussamy|MC|78|titular_base","Edo Kayembe|VOL/MC|78|titular_base","Charles Pickel|VOL|77|titular_base","Yoane Wissa|PE/ATA|83|titular_base","Cédric Bakambu|ATA|80|titular_base","Silas|PD/ATA|81|titular_base","Théo Bongonda|PD/PE|79|reserva_principal","Simon Banza|ATA|80|reserva_principal","Gaël Kakuta|MEI|78|reserva_principal"]},
  {id:"uzb_2026",pais:"Uzbequistão",grupo:"K",jogadores:[
    "Utkir Yusupov|GOL|75|titular_base","Farrukh Sayfiev|LD/LE|75|titular_base","Abdukodir Khusanov|ZAG|82|titular_base","Rustam Ashurmatov|ZAG|76|titular_base","Sherzod Nasrullaev|LE|75|titular_base","Otabek Shukurov|VOL/MC|77|titular_base","Odiljon Hamrobekov|MC|76|titular_base","Jaloliddin Masharipov|MEI/PE|79|titular_base","Abbósbek Fayzullaev|MEI/PD|80|titular_base","Eldor Shomurodov|ATA|80|titular_base","Igor Sergeev|ATA|77|titular_base","Eldorbek Suyunov|GOL|75|reserva_principal","Azizbek Turgunboev|PD|76|reserva_principal","Khojimat Erkinov|PE|76|reserva_principal"]},
  {id:"col_2026",pais:"Colômbia",grupo:"K",jogadores:[
    "Camilo Vargas|GOL|80|titular_base","Daniel Muñoz|LD|82|titular_base","Dávinson Sánchez|ZAG|82|titular_base","Jhon Lucumí|ZAG|82|titular_base","Johan Mojica|LE|79|titular_base","Jefferson Lerma|VOL|81|titular_base","Richard Ríos|MC|81|titular_base","James Rodríguez|MEI|83|titular_base","Luis Díaz|PE|88|titular_base","Jhon Arias|PD/MEI|83|titular_base","Jhon Durán|ATA|84|titular_base","Rafael Santos Borré|ATA|80|reserva_principal","Yaser Asprilla|MEI/PD|80|reserva_principal","Mateus Uribe|MC|79|reserva_principal"]},

  {id:"eng_2026",pais:"Inglaterra",grupo:"L",jogadores:[
    "Jordan Pickford|GOL|84|titular_base","Kyle Walker|LD/ZAG|84|titular_base","John Stones|ZAG|85|titular_base","Marc Guéhi|ZAG|83|titular_base","Luke Shaw|LE|82|titular_base","Declan Rice|VOL/MC|88|titular_base","Jude Bellingham|MEI/MC|91|titular_base","Phil Foden|MEI/PD|89|titular_base","Bukayo Saka|PD|89|titular_base","Harry Kane|ATA|91|titular_base","Cole Palmer|MEI/PD|86|titular_base","Trent Alexander-Arnold|LD/MC|86|reserva_principal","Jack Grealish|PE/MEI|84|reserva_principal","Ollie Watkins|ATA|84|reserva_principal"]},
  {id:"cro_2026",pais:"Croácia",grupo:"L",jogadores:[
    "Dominik Livaković|GOL|82|titular_base","Josip Juranović|LD|80|titular_base","Josip Šutalo|ZAG|82|titular_base","Joško Gvardiol|ZAG/LE|87|titular_base","Borna Sosa|LE/ALA_E|81|titular_base","Marcelo Brozović|VOL|84|titular_base","Luka Modrić|MC/MEI|85|titular_base","Mateo Kovačić|MC|84|titular_base","Lovro Majer|MEI/PD|81|titular_base","Andrej Kramarić|ATA/SA|82|titular_base","Ivan Perišić|PE/ALA_E|80|titular_base","Mario Pašalić|MC/MEI|80|reserva_principal","Luka Sučić|MC/MEI|80|reserva_principal","Ante Budimir|ATA|80|reserva_principal"]},
  {id:"gha_2026",pais:"Gana",grupo:"L",jogadores:[
    "Lawrence Ati-Zigi|GOL|76|titular_base","Alidu Seidu|LD/ZAG|79|titular_base","Daniel Amartey|ZAG|78|titular_base","Mohammed Salisu|ZAG|81|titular_base","Gideon Mensah|LE|77|titular_base","Thomas Partey|VOL/MC|84|titular_base","Majeed Ashimeru|MC|78|titular_base","Mohammed Kudus|MEI/PD|86|titular_base","Jordan Ayew|PD/ATA|79|titular_base","Iñaki Williams|ATA|82|titular_base","Antoine Semenyo|PE/ATA|81|titular_base","André Ayew|SA/PE|77|reserva_principal","Kamaldeen Sulemana|PE|79|reserva_principal","Ernest Nuamah|PD|80|reserva_principal"]},
  {id:"pan_2026",pais:"Panamá",grupo:"L",jogadores:[
    "Luis Mejía|GOL|76|titular_base","Michael Murillo|LD|78|titular_base","Fidel Escobar|ZAG|77|titular_base","Andrés Andrade|ZAG|76|titular_base","Éric Davis|LE|76|titular_base","Aníbal Godoy|VOL|77|titular_base","Adalberto Carrasquilla|MC/MEI|80|titular_base","Cristian Martínez|MC|76|titular_base","Édgar Bárcenas|PD|77|titular_base","José Fajardo|ATA|77|titular_base","César Yanis|PE|76|titular_base","Ismael Díaz|ATA/PE|78|reserva_principal","Cecilio Waterman|ATA|76|reserva_principal","Yoel Bárcenas|PD|75|reserva_principal"]}
];

window.COPA_2026_BASE = window.COPA_2026_BASE.map(selecao => ({
  ...selecao,
  ano: 2026,
  jogadores: selecao.jogadores.map((linha, idx) => {
    const [nome, posicao, overall, tipo] = linha.split("|");
    return { id: `${selecao.id}_${idx}`, nome, posicao, overall: Number(overall), tipo, selecao: selecao.pais };
  })
}));
